[package]
edition = "2021"
name = "tower-keycloak"
version = "0.1.0"

[dependencies]
futures-util = "0.3"
hyper = "0.14"
parking_lot = "0.12"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1", features = ["derive"]}
thiserror = "1.0"
tower-service = "0.3"
tracing = "0.1"